export const MESSAGE_GATE_DECISION_REASONS = [
	"COOLDOWN_ACTIVE",
	"RATE_LIMIT",
	"PLAN_LIMIT",
	"INSTANCE_UNHEALTHY",
	"NO_ELIGIBLE_INSTANCE",
	"POLICY_BLOCKED",
	"UNSUPPORTED_MESSAGE_TYPE",
] as const;

export type MessageGateDecisionReason =
	(typeof MESSAGE_GATE_DECISION_REASONS)[number];

